[package]
name = "intiface-engine"
version = "2.0.3"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "CLI and Library frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-engine.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2021"
exclude = [".vscode/**"]

[lib]
name = "intiface_engine"
path = "src/lib.rs"

[[bin]]
name = "intiface-engine"
path = "src/bin/main.rs"

[features]
default=[]
tokio_console=["console-subscriber"]

[dependencies]
# buttplug = { path = "../buttplug/buttplug" }
# buttplug = "7.1.15"
buttplug = { git = 'https://github.com/blackspherefollower/buttplug-rs', branch = 'loob-support' }
argh = "0.1.12"
log = "0.4.21"
futures = "0.3.30"
tracing-fmt = "0.1.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
tracing = "0.1.40"
tokio = { version = "1.36.0", features = ["sync", "rt-multi-thread", "macros", "io-std", "fs", "signal", "io-util"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
backtrace = "0.3.69"
ctrlc = "3.4.4"
tokio-util = "0.7.10"
serde = "1.0.197"
serde_json = "1.0.114"
thiserror = "1.0.58"
getset = "0.1.2"
async-trait = "0.1.78"
once_cell = "1.19.0"
lazy_static = "1.4.0"
console-subscriber = { version="0.2.0", optional = true }
local-ip-address = "0.5.7"
rand = "0.8.5"
tokio-tungstenite = "0.21.0"
futures-util = "0.3.30"
url = "2.5.0"
libmdns = "0.8.0"

[build-dependencies]
vergen = "7.5.1"
anyhow = "1.0.81"
